### PR TITLE
Valeriia Lukashenko's update of the glossary

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
As per our chat https://github.com/lhcb/glossary/pull/53#issuecomment-957949927, @vlukashenko.

Contributions from Robbert Geertsema and @eduardo-rodrigues.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
> As per our chat [#53 (comment)](https://github.com/lhcb/glossary/pull/53#issuecomment-957949927), @vlukashenko.

OK; no so technical issue. Good to know!

**Comment by eduardo-rodrigues** [comment]
Hi @vlukashenko, so I've added almost everything from your MR https://github.com/lhcb/glossary/pull/53 except for the definition of sWeights, which in fact needs work and is rather text more on sPlots. This could be added later. I have no idea of what is happening with your MR but this one here with minor editorial improvements along the way (as I was copying and pasting bit by bit to try and catch where the failure in https://github.com/lhcb/glossary/pull/53 comes from) builds just fine.

I would be tempted to merge as-is, acknowleding that this is your contribution. The annoying thing is that you would not be bookkept as contributor by GitHub, which is frustrating given all the time you spent on this. You could maybe clone this branch and make a separate MR from your branch and we merge from there? At least then you get counted. Your call :-). Just let me know.

**Comment by vlukashenko** [comment]
> Hi @vlukashenko, so I've added almost everything from your MR #53 except for the definition of sWeights, which in fact needs work and is rather text more on sPlots. This could be added later. I have no idea of what is happening with your MR but this one here with minor editorial improvements along the way (as I was copying and pasting bit by bit to try and catch where the failure in #53 comes from) builds just fine.
> 
> I would be tempted to merge as-is, acknowleding that this is your contribution. The annoying thing is that you would not be bookkept as contributor by GitHub, which is frustrating given all the time you spent on this. You could maybe clone this branch and make a separate MR from your branch and we merge from there? At least then you get counted. Your call :-). Just let me know.

Okay, I will work more on the sWeights then. I should have a good thesis reference somewhere. 

I think you can go ahead and just merge as it is because I am 100% sure I will mess up again something with github. And don't worry, there are a lot of other definitions that I can contribute personally to get my score high! 😄 Just maybe you can also quote Robbert Geertsema as a reviewer for Velopix and Timepix definitions. I will then close the other PR.

**Comment by eduardo-rodrigues** [comment]
OK, thanks.

**Pull request merged**
