### PR TITLE
Use GHAs rather than Travis

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Making use of the Action https://github.com/marketplace/actions/gitbook-action.

### CODE REVIEW

**Comment by henryiii** [comment]
Oh, wow, didn't know there was a gitbook action. Would have suggested a gitbook build + the common deploy action used. If this works, that will be really nice. You'll need to go to branches -> edit -> change the requirements, as well as there might be a button to turn on Actions.

**Comment by eduardo-rodrigues** [comment]
Found what you meant :D. Disabled the requirement so now Travis is no longer required ... Now need to turn Actions on as nothing is running so far ...

**Comment by henryiii** [comment]
I think we'll need to merge to get actions to run, the action file needs to be on the default branch, IIRC.

**Comment by henryiii** [comment]
Also, I'd only publish on runs on master, and maybe just do a test build on PRs?

**Comment by eduardo-rodrigues** [comment]
> Also, I'd only publish on runs on master, and maybe just do a test build on PRs?

What are you suggesting to change? A test on PRs sounds good.

**Comment by henryiii** [comment]
Not sure how to disable the publish in this action. It has too much configuration. :) Though I guess you could publish to a test repo or a different branch, that might be interesting. You can add `if: github.event_name == 'push'` or `pull_request` I believe to filter.

**Comment by eduardo-rodrigues** [comment]
OK, progressing. Now Actions run and I get
```
Run python3 .ci/prepare.py
python3: can't open file '.ci/prepare.py': [Errno 2] No such file or directory
Error: Process completed with exit code 2.
```

**Comment by henryiii** [comment]
You need to checkout before you run anything else that needs the checked out files.

**Comment by henryiii** [comment]
Seems to be working?

**Comment by eduardo-rodrigues** [comment]
> Seems to be working?

Yep 🚀! The test branch got created with all stuff in 👍 !

**Pull request merged**
