### PR TITLE
Add definitions starterkit

### PR DESCRIPTION
**Pull request by vlukashenko**
Added an ntuple definition for Starterkit. @eduardo-rodrigues

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Thanks for this. I will look into the CI failure, which seems to be the same as got in your previous MR :S.

BTW, you ought to link to TTree, https://root.cern/doc/master/classTTree.html, not the rather shortly scoped TNutple, which we do not even use (for obvious reasons).

**Comment by vlukashenko** [comment]
> Thanks for this. I will look into the CI failure, which seems to be the same as got in your previous MR :S.
> 
> BTW, you ought to link to TTree, https://root.cern/doc/master/classTTree.html, not the rather shortly scoped TNutple, which we do not even use (for obvious reasons).

I think the failure is connected to the secrets, where there is a PERSONAL_TOKEN uploaded. I am not entirely sure whether it is okay for non-personal projects. https://github.com/lhcb/glossary/settings/secrets/actions

**Comment by eduardo-rodrigues** [comment]
> I think the failure is connected to the secrets, where there is a PERSONAL_TOKEN uploaded. I am not entirely sure whether it is okay for non-personal projects. https://github.com/lhcb/glossary/settings/secrets/actions

But then why does it work for me and not for you? And various other people committed. Dunno if somebody of the admins has an idea?

**Comment by vlukashenko** [comment]
> > I think the failure is connected to the secrets, where there is a PERSONAL_TOKEN uploaded. I am not entirely sure whether it is okay for non-personal projects. https://github.com/lhcb/glossary/settings/secrets/actions
> 
> But then why does it work for me and not for you? And various other people committed. Dunno if somebody of the admins has an idea?

I can try to upload my token there now and see what will happen then

**Comment by eduardo-rodrigues** [comment]
Closing in favour of the more complete https://github.com/lhcb/glossary/pull/56.

**Pull request closed without merging**
